export const money = (number: number) => {
  return new Intl.NumberFormat("en-US", {
    style: "currency",
    currency: "USD",
  }).format(number / 100);
};

export const cma = (str: string) => str.split(",").reverse().join(" ");

export const nato = (s: string): string => {
  if (!s) return "";
  const h: Record<string, string> = {
    A: "Alpha",
    B: "Bravo",
    C: "Charlie",
    D: "Delta",
    E: "Echo",
    F: "Foxtrot",
    G: "Golf",
    H: "Hotel",
    I: "India",
    J: "Juliett",
    K: "Kilo",
    L: "Lima",
    M: "Mike",
    N: "November",
    O: "Oscar",
    P: "Papa",
    Q: "Quebec",
    R: "Romeo",
    S: "Sierra",
    T: "Tango",
    U: "Uniform",
    V: "Victor",
    W: "Whiskey",
    X: "X-ray",
    Y: "Yankee",
    Z: "Zulu",
  };
  return [...s.toUpperCase().split("")].map((x) => h[x] ?? x).join(" ");
};

export const CROP_MAPPING: Record<string, string> = {
  "3079": "Brussels Sprouts",
  "3089": "Melon, Watermelon",
  "3091": "Melon, Honeydew",
  "3095": "Melon, Watermelon Red Seedless",
  "3099": "Beets w/greens",
  "3105": "Cabbage, Green, Organic",
  "3107": "Carrots, Foodservice/Jumbo, Organic",
  "3132": "Carrots, Rainbow Bulk",
  "3134": "Sweet Corn, Organic",
  "3135": "Sweet Corn",
  "3138": "Greens, Collards",
  "3140": "Kohlrabi, White",
  "3141": "Onions, Red, Organic",
  "3153": "Peppers, Jalapeño",
  "3166": "Potatoes, Red",
  "3171": "Potatoes, Yellow",
  "3178": "Radishes, Daikon",
  "3180": "Radish, Watermelon",
  "3184": "Squash, Summer, Zucchini",
  "3188": "Squash, Winter, Butternut",
  "3189": "Squash, Winter, Delicata",
  "3190": "Squash, Winter, Spaghetti",
  "3200": "Tomatoes, Grape",
  "3201": "Tomatoes, Roma",
  "3202": "Tomatoes, Slicers",
  "3216": "Rhubarb",
  "3242": "Greens, Lettuce, Romaine, Green, Organic",
  "3252": "Radish, French Breakfast",
  "3266": "Onions, Scallions",
  "3278": "Radish, Red, Bunched w/Tops",
  "3300": "Greens, Lettuce, Salad Mix",
  "3304": "Garlic Scapes",
  "3316": "Greens, Lettuce, Green Leaf",
  "3326": "Fennel",
  "3361": "Cucumbers, Slicing",
  "3362": "Cucumbers, Pickling",
  "3364": "Greens, Mustard",
  "3390": "Potatoes, New Red",
  "3401": "Beans, Green",
  "3404": "Tomatillos",
  "3405": "Okra",
  "3411": "Greens, Bok Choy, Baby",
  "3449": "Peppers, Poblano",
  "3458": "Peppers, Habanero",
  "3539": "Ground Cherries",
  "3544": "Squash, Winter, Acorn",
  "3573": "Bok Choi",
  "3579": "Celery, Organic",
  "3592": "Broccoli",
  "3598": "Greens, Lettuce, Romaine",
  "3613": "Beets, Red, Organic",
  "3668": "Eggplant, Japanese",
  "3669": "Greens, Chard",
  "3700": "Greens, Spinach, Chinese water spinach",
  "3702": "Greens, Malabar",
  "3717": "Eggplant, Globe",
  "3733": "Melon, Cantaloupe",
  "3754": "Cabbage",
  "3755": "Carrots",
  "3756": "Cucumbers",
  "3757": "Eggplant",
  "3758": "Eggplant, African Bitter Ball",
  "3759": "Onions",
  "3768": "Cranberries, organic",
  "3775": "Kohlrabi",
  "3806": "Greens, Lettuce, Head",
  "3807": "Cauliflower",
  "3809": "Beans, Green, Yellow or Purple",
  "3813": "Greens, Kale",
  "3819": "Greens, Salad Mix - 24 ct 0.75lb",
  "3826": "Greens, Sweet Potato Leaves",
  "3828": "Peppers, Bell",
  "3853": "Greens, Eggplant-12 ct ",
  "3854": "Greens, Pumpkin Vine",
  "9997": "Radishes, Watermelon",
  "9998": "Greens, Spinach",
  "9999": "Cilantro",
};

export const FARMS = [
  "None",
  "POG",
  "STF",
  "WKH",
  "YMF",
  "HAF",
  "NTN",
  "SGC",
  "CVP",
  "CHO",
  "KLF",
  "LXF",
  "CBS",
  "SEE",
  "MLF",
  "MHG",
  "MKV",
  "AFC",
  "MLG",
  "PBY",
  "CLP",
  "PLT",
  "SXF",
  "KHF",
  "MLP",
  "KSL",
  "DTF",
  "RSV",
  "OHF",
  "CMA",
  "CBO",
  "CMU",
  "TEB",
  "LVO",
  "JWI",
  "ONC",
  "TXI",
  "LOF",
  "MMO",
  "PZM",
  "LEE",
  "MHA",
  "LDX",
  "AGF",
  "BXF",
  "SRF",
  "LFF",
  "HOP",
  "MFP",
  "CAL",
  "CTH",
  "LKW",
  "UNK",
  "KAL",
];
